//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleTracking.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dXMuuu5IUUO0EAeoRWUQ~a5xyce-TWMN1LUpg48g3Pg~AjDTPUxypaLVEfJFh8_TdMZaHKZ9XU0vnScBf" +
            "yre6dHV7C5ui4v-6Oo3nEC4G6M0")]
        public string VihicleTracking {
            get {
                return ((string)(this["VihicleTracking"]));
            }
            set {
                this["VihicleTracking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Https")]
        public global::DevExpress.XtraMap.ConnectionProtocol abc {
            get {
                return ((global::DevExpress.XtraMap.ConnectionProtocol)(this["abc"]));
            }
            set {
                this["abc"] = value;
            }
        }
    }
}
